name: test feature 1

on:
   push: 
    branches: 
      - feature1

jobs:
  test_f1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: npm i 
      - run: npm test 


