name: test build deploy to production

on:
   push: 
    branches: 
      - main

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: npm ci 
      - run: npm test 
      - run: npm run build 


