name: test production

on:
   pull_request: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: npm i 
      - run: npm test
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "prdu" #Must be unique in Heroku
          heroku_email: "jmambrinventre@gmail.com"



