<<<<<<< HEAD:.github/workflows/production.yaml
name: test build deploy to production
=======
name: test develop 
>>>>>>> develop:.github/workflows/develop.yaml

on:
   push: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: npm i 
      - run: npm test

  deploy: 
    name: deploy to production
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "prdu" #Must be unique in Heroku
          heroku_email: "jmambrinventre@gmail.com"


